---

- name: Create portage repos.conf directory
  file:
    path: '/etc/portage/repos.conf'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Gentoo portage repository configuration
  template:
    src: 'repos.conf-gentoo.conf.j2'
    dest: '/etc/portage/repos.conf/gentoo.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: gentoo_register_portage_config

- name: Global USE flags configuration
  lineinfile:
    path: '/etc/portage/make.conf'
    regexp: '^USE='
    line: |
      USE="{{ (gentoo_use_enable_global | sort | join(' ')) + ' '
              if (gentoo_use_enable_global | length > 0)
              else '' }}{{
              ('-' + gentoo_use_disable_global | sort | join (' -'))
              if (gentoo_use_disable_global | length > 0)
              else '' }}"

- name: Check if equery is available
  command: which equery
  check_mode: no
  changed_when: False
  failed_when: False
  register: gentoo_register_equery

- name: Install gentoolkit for equery support
  command: emerge gentoolkit
  when: gentoo_register_equery.rc != 0

- name: Synchronize portage repository
  portage:
    sync: yes
  when: ((gentoo_register_portage_config is changed) and
         (gentoo_portage_sync_repo | bool)) or
        (gentoo_portage_force_sync | bool)

- name: Install packages
  package:
    name: '{{ gentoo_packages_default | union(gentoo_packages) }}'
    state: present
  register: gentoo_register_package_install

- name: Cleanup package sources after installation
  command: eclean-dist
  when:
    - gentoo_register_package_install is changed
    - gentoo_packages_clean_sources | bool
